/**
 * Reconstructed from WAWebMsgType module: static.whatsapp.net/rsrc.php/X4jui8q359-.js
 */
export enum MSG_TYPE {
    BROADCAST_NOTIFICATION = "broadcast_notification",
    CALL_LOG = "call_log",
    E2E_NOTIFICATION = "e2e_notification",
    GP2 = "gp2",
    HISTORY_BUNDLE = "history_bundle",
    NEWSLETTER_NOTIFICATION = "newsletter_notification",
    NOTIFICATION = "notification",
    NOTIFICATION_TEMPLATE = "notification_template",
    PROTOCOL = "protocol",
    ALBUM = "album",
    AUDIO = "audio",
    AUTOMATED_GREETING_MESSAGE = "automated_greeting_message",
    BIZ_CONTENT_PLACEHOLDER = "biz_content_placeholder",
    BIZ_COVER_PHOTO = "biz-cover-photo",
    BUTTONS_RESPONSE = "buttons_response",
    CHAT = "chat",
    CIPHERTEXT = "ciphertext",
    COMMENT = "comment",
    DEBUG = "debug",
    DEBUG_PLACEHOLDER = "debug_placeholder",
    DOCUMENT = "document",
    EVENT_CREATION = "event_creation",
    EVENT_EDIT_ENCRYPTED = "event_edit_encrypted",
    EVENT_RESPONSE = "event_response",
    GROUPS_V4_INVITE = "groups_v4_invite",
    HSM = "hsm",
    IMAGE = "image",
    INTERACTIVE = "interactive",
    INTERACTIVE_RESPONSE = "interactive_response",
    KEEP_IN_CHAT = "keep_in_chat",
    LIST = "list",
    LIST_RESPONSE = "list_response",
    LOCATION = "location",
    MULTI_VCARD = "multi_vcard",
    NATIVE_FLOW = "native_flow",
    NEWSLETTER_ADMIN_INVITE = "newsletter_admin_invite",
    ORDER = "order",
    OVERSIZED = "oversized",
    PAYMENT = "payment",
    PIN_MESSAGE = "pin_message",
    PINNED_MESSAGE = "pinned_message",
    POLL_CREATION = "poll_creation",
    POLL_RESULT_SNAPSHOT = "poll_result_snapshot",
    POLL_UPDATE = "poll_update",
    PRODUCT = "product",
    PTT = "ptt",
    PTV = "ptv",
    REACTION = "reaction",
    REACTION_ENC = "reaction_enc",
    REQUEST_PHONE_NUMBER = "request_phone_number",
    REVOKED = "revoked",
    RICH_RESPONSE = "rich_response",
    STATUS = "status",
    STATUS_NOTIFICATION = "status_notification",
    STICKER = "sticker",
    STICKER_PACK = "sticker-pack",
    TEMPLATE_BUTTON_REPLY = "template_button_reply",
    UNKNOWN = "unknown",
    VCARD = "vcard",
    VIDEO = "video",
}

export const ALL_MSG_TYPES_SET = new Set(
    Object.keys(MSG_TYPE).map(function (a) {
        return MSG_TYPE[a];
    })
);
export const SYSTEM_MESSAGE_TYPES = [
    "broadcast_notification",
    "call_log",
    "debug",
    "e2e_notification",
    "gp2",
    "newsletter_notification",
    "notification",
    "notification_template",
    "protocol",
    "pinned_message",
];
export enum MsgKind {
    Album = "album",
    AssociatedImage = "associatedImage",
    AssociatedUnknown = "associatedUnknown",
    AssociatedVideo = "associatedVideo",
    Audio = "audio",
    AutomatedGreetingMessage = "automatedGreetingMessage",
    BizContentPlaceholder = "bizContentPlaceholder",
    BizCoverPhoto = "bizCoverPhoto",
    BroadcastNotification = "broadcastNotification",
    ButtonsResponse = "buttonsResponse",
    CallLog = "callLog",
    Chat = "chat",
    Ciphertext = "ciphertext",
    CommentDecrypted = "commentDecrypted",
    CommentEncrypted = "commentEncrypted",
    Debug = "debug",
    DebugPlaceholder = "debugPlaceholder",
    Document = "document",
    E2eNotification = "e2eNotification",
    EventCreation = "eventCreation",
    EventEditDecrypted = "eventEditDecrypted",
    EventEditEncrypted = "eventEditEncrypted",
    EventResponseDecrypted = "eventResponseDecrypted",
    EventResponseEncrypted = "eventResponseEncrypted",
    Gp2 = "gp2",
    GroupsV4Invite = "groupsV4Invite",
    Historybundle = "historyBundle",
    Hsm = "hsm",
    Image = "image",
    Interactive = "interactive",
    InteractiveResponse = "interactiveResponse",
    KeepInChat = "keepInChat",
    List = "list",
    ListResponse = "listResponse",
    Location = "location",
    LocationLive = "locationLive",
    MultiVcard = "multiVcard",
    NativeFlow = "nativeFlow",
    NewsletterAdminInvite = "newsletterAdminInvite",
    NewsletterNotification = "newsletterNotification",
    Notification = "notification",
    NotificationTemplate = "notificationTemplate",
    Order = "order",
    Oversized = "oversized",
    Payment = "payment",
    PeerMessage = "peerMessage",
    PinInChat = "pinInChat",
    PlaceholderMessage = "placeholderMessage",
    PlaceholderAddon = "placeholderAddon",
    PinnedMessage = "pinnedMessage",
    PollCreation = "pollCreation",
    PollResultSnapshot = "pollResultSnapshot",
    PollVoteDecrypted = "pollVoteDecrypted",
    PollVoteEncrypted = "pollVoteEncrypted",
    Product = "product",
    Protocol = "protocol",
    ProtocolAddonRevoke = "protocolAddonRevoke",
    ProtocolEventEdit = "protocolEventEdit",
    ProtocolRevoke = "protocolRevoke",
    Ptt = "ptt",
    Ptv = "ptv",
    ReactionDecrypted = "reactionDecrypted",
    ReactionEncrypted = "reactionEncrypted",
    RequestPhoneNumber = "requestPhoneNumber",
    RevokedAddon = "revokedAddon",
    RevokedMessage = "revokedMessage",
    RichResponse = "richResponse",
    Sticker = "sticker",
    StickerPack = "stickerPack",
    Status = "status",
    TemplateButtonReply = "templateButtonReply",
    Unknown = "unknown",
    Vcard = "vcard",
    Video = "video",
}
